disabled_rules:
- trailing_whitespace
- identifier_name
- opening_brace
- nesting

opt_in_rules:
- sorted_imports
- explicit_acl
- explicit_top_level_acl

analyzer_rules:
- unused_import

line_length:
  ignores_comments: true
